--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/galaxytwenty/PmGPT
build-by-default: true
branches:
- main
projects:
  PmGPT:
    path: ""
    icon: icon.png
    libs:
      - src: https://poggit.pmmp.io/ci/supercrafter333/FormAPI/libFormAPI
        version: ^2.1.0
...
